// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'E:/FindJob/值得学习的项目/组件库/kwaii-ui/node_modules/dumi/theme-default/slots/Header/index.js';
